### ISSUE TITLE
Crash on python method

### ISSUE THREAD

**Issue by tbreloff** [stevengj/PyCall.jl#301]
I'm trying to get my OpenAIGym.jl working, but I'm getting consistent crashes when trying to render.  This example works in python:

```
import gym
env = gym.make('CartPole-v0')
env.reset()
env.render()
```

But the equivalent using PyCall:

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-pre+5702 (2016-07-26 13:44 UTC)
 _/ |\__'_|_|_|\__'_|  |  tb_pkgsha/fc1eac3 (fork: 1 commits, 2 days)
|__/                   |  x86_64-linux-gnu

julia> using PyCall

julia> @pyimport gym

julia> env = gym.make("CartPole-v0")
[2016-07-28 16:06:44,669] Making new env: CartPole-v0
PyObject <gym.envs.classic_control.cartpole.CartPoleEnv object at 0x7fbaea6c79d0>

julia> env[:reset]()
4-element Array{Float64,1}:
 -0.0380367
 -0.0192369
  0.0102265
 -0.0400403

julia> env[:render]()

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
macro expansion at /home/tom/.julia/v0.5/PyCall/src/exception.jl:78 [inlined]
macro expansion at /home/tom/.julia/v0.5/PyCall/src/exception.jl:549 [inlined]
#pycall#62 at /home/tom/.julia/v0.5/PyCall/src/PyCall.jl:544
#call#65 at /home/tom/.julia/v0.5/PyCall/src/PyCall.jl:564
PyObject at /home/tom/.julia/v0.5/PyCall/src/PyCall.jl:564
jl_call_method_internal at /opt/julia5/src/julia_internal.h:178 [inlined]
jl_apply_generic at /opt/julia5/src/gf.c:2034
do_call at /opt/julia5/src/interpreter.c:66
eval at /opt/julia5/src/interpreter.c:190
jl_toplevel_eval_flex at /opt/julia5/src/toplevel.c:558 [inlined]
jl_toplevel_eval at /opt/julia5/src/toplevel.c:580
jl_toplevel_eval_in_warn at /opt/julia5/src/builtins.c:576
eval at ./boot.jl:234
jl_call_method_internal at /opt/julia5/src/julia_internal.h:178 [inlined]
jl_apply_generic at /opt/julia5/src/gf.c:2034
eval_user_input at ./REPL.jl:62
jl_call_method_internal at /opt/julia5/src/julia_internal.h:178 [inlined]
jl_apply_generic at /opt/julia5/src/gf.c:2034
macro expansion at ./REPL.jl:92 [inlined]
#3 at ./event.jl:46
jl_call_method_internal at /opt/julia5/src/julia_internal.h:178 [inlined]
jl_apply_generic at /opt/julia5/src/gf.c:2034
jl_apply at /opt/julia5/src/julia.h:1394 [inlined]
start_task at /opt/julia5/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 4002865 (Pool: 4000838; Big: 2027); GC: 5
Segmentation fault (core dumped)
```

Any idea what might be causing this?

```
 - PyCall                        1.6.3+   494f8316  master
```

**Comment by tbreloff** [comment]
I was able to reduce the problem... this crashes:

```
using PyCall
@pyimport pyglet
```

```
signal (11): Segmentation fault
while loading no file, in expression starting on line 382
getindex at /home/tom/.julia/v0.5/PyCall/src/PyCall.jl:270
pysequence_query at /home/tom/.julia/v0.5/PyCall/src/conversions.jl:729
pytype_query at /home/tom/.julia/v0.5/PyCall/src/conversions.jl:745
convert at /home/tom/.julia/v0.5/PyCall/src/conversions.jl:794
#55 at ./<missing>:0 [inlined]
next at ./generator.jl:26 [inlined]
collect_to! at ./array.jl:303
collect at ./array.jl:272
jl_call_method_internal at /opt/julia5/src/julia_internal.h:178 [inlined]
jl_apply_generic at /opt/julia5/src/gf.c:1930
pywrap at /home/tom/.julia/v0.5/PyCall/src/PyCall.jl:326
pywrap at /home/tom/.julia/v0.5/PyCall/src/PyCall.jl:322
jl_call_method_internal at /opt/julia5/src/julia_internal.h:178 [inlined]
jl_apply_generic at /opt/julia5/src/gf.c:1930
do_call at /opt/julia5/src/interpreter.c:66
eval at /opt/julia5/src/interpreter.c:190
eval_body at /opt/julia5/src/interpreter.c:469
jl_toplevel_eval_flex at /opt/julia5/src/toplevel.c:552
jl_toplevel_eval_flex at /opt/julia5/src/toplevel.c:533 [inlined]
jl_toplevel_eval at /opt/julia5/src/toplevel.c:580
jl_toplevel_eval_in_warn at /opt/julia5/src/builtins.c:576
eval at ./boot.jl:234
jl_call_method_internal at /opt/julia5/src/julia_internal.h:178 [inlined]
jl_apply_generic at /opt/julia5/src/gf.c:1930
eval_user_input at ./REPL.jl:64
jl_call_method_internal at /opt/julia5/src/julia_internal.h:178 [inlined]
jl_apply_generic at /opt/julia5/src/gf.c:1930
macro expansion at ./REPL.jl:95 [inlined]
#3 at ./event.jl:46
jl_call_method_internal at /opt/julia5/src/julia_internal.h:178 [inlined]
jl_apply_generic at /opt/julia5/src/gf.c:1930
jl_apply at /opt/julia5/src/julia.h:1392 [inlined]
start_task at /opt/julia5/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 3512001 (Pool: 3509858; Big: 2143); GC: 4
Segmentation fault (core dumped)
```

If you have any ideas of how to debug this, please let me know.  Thanks.

**Comment by tbreloff** [comment]
Adding some debugging lines, it seems that it might be crashing while processing this tuple:

```
tup = ("event",PyObject <pyglet._ModuleProxy object at 0x7fa8627b6e50>)
```

during the "getmembers" conversion in `pywrap`: https://github.com/stevengj/PyCall.jl/blob/master/src/PyCall.jl#L309-L310

**Comment by stevengj** [comment]
Does it work if you just do `pyglet = pyimport("pyglet")`?   (I wouldn't normally recommend using `@pyimport` in modules, since it doesn't mesh well with precompilation.

**Comment by tbreloff** [comment]
`using PyCall; pyglet = pyimport("pyglet")` did work without error, however the original example still crashes in the same spot (after a call to `env[:render]()`), even with the pyimport change.

With some print statements, it seems that the crash happens in the following call:

```
ccall(@pysym(:PyObject_Call),PyPtr,(PyPtr,PyPtr,PyPtr),o,arg,C_NULL)
```

which happens [here](https://github.com/stevengj/PyCall.jl/blob/master/src/exception.jl#L78).  The values:

```
o = PyObject <bound method CartPoleEnv.render of <gym.envs.classic_control.cartpole.CartPoleEnv object at 0x7f0518837990>>
arg = PyObject ()
```

If you can think of any other debugging tactics, please let me know.  Thanks

**Comment by stevengj** [comment]
My usual guess on this sort of thing is that it is some kind of shared-library conflict.  i.e. `python` is loading a different version of some shared library than `julia`, and the mismatch between what Python is expecting and what it is calling is causing the crash...

**Comment by tbreloff** [comment]
Yeah that's my thinking as well.  I'm just having a hard time figuring out which library and how to fix it.  Thanks for the help so far @stevengj.   Can you think of any changes recently that would cause this issue?  Were there any changes to how libraries are chosen/loaded in PyCall?

**Comment by tbreloff** [comment]
I think I've narrowed this to LLVM libs.  I wonder why both `libLLVM-3.7.1.so` and `libLLVM-3.6.so.1` are loaded?

```
(gdb) bt
#0  0x00007f9a737b1be1 in llvm::cl::AddLiteralOption(llvm::cl::Option&, char const*) ()
   from /opt/julia5/usr/bin/../lib/libLLVM-3.7.1.so
#1  0x00007f983e39c199 in llvm::PassRegistry::enumerateWith(llvm::PassRegistrationListener*) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1
#2  0x00007f983e06c686 in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1
#3  0x00007f9a75cb75ca in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7ffd9046cce8, 
    env=env@entry=0x3c74b20) at dl-init.c:72
#4  0x00007f9a75cb76db in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, 
    l=<optimized out>) at dl-init.c:30
#5  _dl_init (main_map=main_map@entry=0x501bae0, argc=1, argv=0x7ffd9046cce8, env=0x3c74b20) at dl-init.c:120
#6  0x00007f9a75cbc597 in dl_open_worker (a=a@entry=0x7ffd90468438) at dl-open.c:579
#7  0x00007f9a75cb7474 in _dl_catch_error (objname=objname@entry=0x7ffd90468428, 
    errstring=errstring@entry=0x7ffd90468430, mallocedp=mallocedp@entry=0x7ffd90468427, 
    operate=operate@entry=0x7f9a75cbc0b0 <dl_open_worker>, args=args@entry=0x7ffd90468438) at dl-error.c:187
#8  0x00007f9a75cbb9b3 in _dl_open (file=0x7ffd904686a0 "/usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so", 
    mode=-2147483390, caller_dlopen=0x7f98698c7439, nsid=-2, argc=<optimized out>, argv=<optimized out>, 
    env=0x3c74b20) at dl-open.c:663
#9  0x00007f9a7549efc9 in dlopen_doit (a=a@entry=0x7ffd90468650) at dlopen.c:66
#10 0x00007f9a75cb7474 in _dl_catch_error (objname=0x1c70440, errstring=0x1c70448, mallocedp=0x1c70438, 
    operate=0x7f9a7549ef70 <dlopen_doit>, args=0x7ffd90468650) at dl-error.c:187
#11 0x00007f9a7549f62d in _dlerror_run (operate=operate@entry=0x7f9a7549ef70 <dlopen_doit>, 
    args=args@entry=0x7ffd90468650) at dlerror.c:163
#12 0x00007f9a7549f061 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#13 0x00007f98698c7439 in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#14 0x00007f98698ca255 in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#15 0x00007f98698a28a4 in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#16 0x00007f986989e041 in glXQueryVersion () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#17 0x00007f98562d8d90 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#18 0x00007f98562d87f8 in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#19 0x00007f9856506bbf in _ctypes_callproc () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#20 0x00007f985650aea4 in ?? () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#21 0x00007f9856bbd933 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#22 0x00007f9856b4b602 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#23 0x00007f9856b4e1c0 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#24 0x00007f9856c8508c in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#25 0x00007f9856b4df3f in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#26 0x00007f9856b4e1c0 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#27 0x00007f9856b4e1c0 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#28 0x00007f9856c8508c in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#29 0x00007f9856b4df3f in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#30 0x00007f9856c8508c in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#31 0x00007f9856c070bd in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#32 0x00007f9856bbd933 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#33 0x00007f9856b49d9f in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#34 0x00007f9856c8508c in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#35 0x00007f9856c070bd in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#36 0x00007f9856bbd933 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#37 0x00007f9856c2ee9c in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#38 0x00007f9856bbd933 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#39 0x00007f9856be09ed in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#40 0x00007f9856b7371f in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#41 0x00007f9856bbd933 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#42 0x00007f9856b4b602 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#43 0x00007f9856b4e1c0 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#44 0x00007f9856c8508c in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#45 0x00007f9856b45d09 in PyEval_EvalCode () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#46 0x00007f9856bb4e64 in PyImport_ExecCodeModuleEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#47 0x00007f9856bb583f in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#48 0x00007f9856bb67e2 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
#49 0x00007f9856bb6fb0 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so
```

**Comment by stevengj** [comment]
Does pyglet use LLVMPy or similar?

**Comment by stevengj** [comment]
Maybe your OpenGL backend uses LLVM, e.g. maybe you are using http://www.mesa3d.org/llvmpipe.html?

**Comment by tbreloff** [comment]
This seems like the likely culprit, and I have no idea how to get around it.  I think it's easier to build from scratch in Julia rather than debug system libraries... I can close this because I just don't have any more time to spend on it.
